### PR TITLE
Avoiding race condition when concurrently creating the same parameters.

### PR DESCRIPTION
**Pull request by bwanner**
If the same parameters are added concurrently this can result in an `_usableParameters.Add()` call when the key already exists.

Quick fix: Adding lock to avoid this.

### CODE REVIEW

**Comment by mcintyre321** [comment]
Cheers!

Any thoughts on lock vs ConcurrentDictionary?

Out of interest, what are you using MetaLinq for?

**Comment by bwanner** [comment]
Thanks for the quick merge and publishing that project!

Indeed ConcurrentDictionary would look better, just thought it might be overkill to add another dependency just for using this once.

I'm implementing a streaming-approach to distributed and incremental query evaluation. I use MetaLinq to transfer expressions across multiple systems since the incremental evaluation caches intermediate results based on an expression tree.
You can see features of it being used [here ](https://github.com/OrleansContrib/Orleans.Containers/blob/property-changed-support/Orleans.Streams/SerializableFunc.cs) to transfer the expressions used within LINQ's  Select/Where methods.

**Comment by mcintyre321** [comment]
VERY intereresting!

Are you familiar with [OLinq](https://github.com/wasabii/OLinq), which lets you do (non-distributed) incremental LINQ queries? I've used it for projections inside an event-sourced aggregate.

**Comment by bwanner** [comment]
I did not hear of OLinq so far, that looks interesting! I'm relying on NMF Expressions ([Docs](https://nmfexpressions.codeplex.com/) | [Code](https://github.com/NMFCode/NMF)), which was developed by my thesis advisor and provides similar functionality.

What you've done sounds related to what I'm doing right now, did you open source any of this?

**Comment by mcintyre321** [comment]
The application isn't public, but I have a extracted few projects which are related: 
- [Sourcery](https://github.com/mcintyre321/Sourcery) my event sourcing lib, records and replays events against an object instance. Maybe not needed if you are using an Actor framework and one of the EventSourcing libraries
- [Linqdex](https://github.com/mcintyre321/Linqdex) basically binds in memory lucene indexes to INotifyCollecitionChange via [Lucene.Net.Linq](https://github.com/themotleyfool/Lucene.Net.Linq) so that I can do fast searches against the projected data. 

My application basically has a single Sourcery aggregate instance in it, which I keep alive for the lifetime of the app. If it crashes, Sourcery rebuilds it (takes a few minutes to run through the 10000 events! need to optimize or snapshot).

As it rebuilds, the events add data into ObservableCollections, and I build projections up using OLinq and Linqdex.

Part of me wonders if I just need a single ObservableColleciton<EventData> for storing all event data, and then I can project the entire application off that using .Aggregate...

**Comment by bwanner** [comment]
I see how event sourcing and ObservableCollections play together nicely, what I am doing now is similar:

A query is created against a data model while each query operator is able to keep its individual read-only copy. Changes to a master data model are applied and passed through the system (right now I'm just passing the `Func` to be executed assuming that it is available to the query operator). It could make sense to combine that with "real" event sourcing in the future.

**Pull request merged**
